script:
- set -o pipefail && xcodebuild test -workspace LHSKeyboardAdjustingExample/LHSKeyboardAdjustingExample.xcworkspace -scheme LHSKeyboardAdjustingExample -destination "platform=iOS Simulator,name=iPhone 5s" -destination-timeout 1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

language: objective-c
osx_image: xcode7.3
