language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: LHSKeyboardAdjustingExample/Podfile

before_install:
- gem install cocoapods
- pod install --project-directory=LHSKeyboardAdjustingExample

script:
- set -o pipefail && xcodebuild test -workspace LHSKeyboardAdjustingExample/LHSKeyboardAdjustingExample.xcworkspace -scheme LHSKeyboardAdjustingExample -destination "platform=iOS Simulator,name=iPhone 5s" -destination-timeout 1 -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

